<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPageLoggedUser.master" AutoEventWireup="true" CodeFile="MyCart.aspx.cs" Inherits="MyCart" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>

<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">
<br />
    <asp:GridView ID="GridView1" runat="server" EnableModelValidation="True" 
        AutoGenerateColumns="False" AutoGenerateDeleteButton="True" Caption="Your Cart" 
        CellPadding="4" DataSourceID="SqlDataSource1" GridLines="None" 
        AutoGenerateEditButton="True" DataKeyNames="Product_Id" 
        onrowdeleting="GridView1_RowDeleting" CssClass="center" 
        ForeColor="#333333">
        <AlternatingRowStyle BackColor="White" />
        <Columns>
            <asp:BoundField DataField="Product_Name" HeaderText="Product_Name" 
                SortExpression="Product_Name" ReadOnly="true"/>
            <asp:BoundField DataField="Price" HeaderText="Price" SortExpression="Price" ReadOnly="true" />
            <asp:BoundField DataField="Description" HeaderText="Description" 
                SortExpression="Description" ReadOnly="true" />
            <asp:BoundField DataField="Quantity" HeaderText="Quantity" 
                SortExpression="Quantity" />
            <asp:ImageField DataImageUrlField="Image" ReadOnly="true">
            </asp:ImageField>
        </Columns>
        
        <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
        <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
        <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
        
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:ShoppingCart1ConnectionString %>" 
        
        SelectCommand="SELECT [Product Name] AS Product_Name, [Price], [Description], [Quantity], [Image], [Product Id] AS Product_Id FROM [MyCart] WHERE ([LoginName] = @LoginName)" 
        DeleteCommand="delete from Mycart where [Product Id]=@Product_Id" 
        UpdateCommand="update mycart set quantity=@quantity where [Product Id]=@Product_Id">
        <DeleteParameters>
            <asp:Parameter Name="Product_Id" />
        </DeleteParameters>
        <SelectParameters>
            <asp:SessionParameter DefaultValue="null" Name="LoginName" SessionField="Login" 
                Type="String" />
        </SelectParameters>
        <UpdateParameters>
            <asp:Parameter Name="quantity" />
            <asp:Parameter Name="Product_Id" />
        </UpdateParameters>
    </asp:SqlDataSource>
    <br />
    <div class="center">
    <asp:Button ID="Button1" runat="server" onclick="Button1_Click" 
        Text="Return To Home Page" />
        </div>
</asp:Content>

